spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pneuservis
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



