#logging:
#  level:
#    org.flywaydb: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pneuservis
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



