services:
  db:
    container_name: postgres-daniil
    image: postgres
    environment:
      POSTGRES_USER: forh
      POSTGRES_PASSWORD: hak
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: